<?php
declare(strict_types=1);
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
require __DIR__ . '/../lib/WifiNetworkGroups.php';
$n=0;
function check(bool $ok, string $name): void { global $n; $n++; if(!$ok) throw new RuntimeException('FAIL: '.$name); }
function put(array &$device, string $path, mixed $value, bool $writable=false): void {
    $node=&$device;
    foreach(explode('.',$path) as $part){$node[$part]??=[];$node=&$node[$part];}
    $node=['_value'=>$value,'_type'=>is_bool($value)?'xsd:boolean':'xsd:string','_writable'=>$writable,'_timestamp'=>'2026-09-20T12:00:00Z'];
}
$d=['_deviceId'=>['_Manufacturer'=>'FixtureVendor','_ProductClass'=>'FixtureAX','_SerialNumber'=>'PRIVATE-SERIAL']];
put($d,'Device.DeviceInfo.SoftwareVersion','TEST-1');
put($d,'Device.WiFi.Radio.1.SupportedStandards','b,g,n,ax');
put($d,'Device.WiFi.Radio.1.OperatingStandards','bgnax');
put($d,'Device.WiFi.Radio.1.OperatingFrequencyBand','2.4GHz');
put($d,'Device.WiFi.Radio.2.OperatingStandards','a,n,ac,ax');
put($d,'Device.WiFi.Radio.2.OperatingFrequencyBand','5GHz');
put($d,'Device.WiFi.SSID.1.SSID','SECRET-SSID');
put($d,'Device.WiFi.SSID.2.SSID','SECRET-SSID');
put($d,'Device.WiFi.AccessPoint.1.Security.KeyPassphrase','SECRET-PASSWORD',true);
$x=(new WifiNetworkGroups($d))->inspect();
check($x['schema']==='wifi-network-groups-v1','schema');
check($x['read_only']===true,'read only');
check($x['device']['firmware']==='TEST-1','firmware');
check(in_array('ax',$x['technology']['supported'],true),'reported support');
check(in_array('ax',$x['technology']['configured'],true),'reported configured');
check($x['bands_reported']===['2.4','5'],'separate bands');
check($x['unified']['state']==='not_reported','same SSID not unified proof');
check($x['mlo']['candidate_count']===0,'ax not MLO');
check(!str_contains(json_encode($x),'SECRET-SSID'),'SSID not exported');
check(!str_contains(json_encode($x),'SECRET-PASSWORD'),'password not exported');
check(!str_contains(json_encode($x),'PRIVATE-SERIAL'),'serial not exported');
put($d,'Device.WiFi.X_TEST_BandSteering.Enable',true,true);
put($d,'Device.WiFi.X_TEST_BandSteering.SSID','GROUP-SSID',true);
put($d,'Device.WiFi.X_TEST_BandSteering.Password','GROUP-SECRET',true);
$x=(new WifiNetworkGroups($d))->inspect();
check($x['unified']['state']==='mapping_required','candidate requires mapping');
check($x['unified']['candidate_count']===3,'candidate fields collected');
check($x['unified']['can_manage']===false,'writable candidate not enabled');
check(!str_contains(json_encode($x),'GROUP-SSID'),'group SSID not exported');
check(!str_contains(json_encode($x),'GROUP-SECRET'),'group password not exported');
check($x['parameters'][0]['writable_reported']===true,'writability metadata');
check(!array_key_exists('value',$x['parameters'][0]),'no raw values');
put($d,'Device.WiFi.Radio.2.SupportedStandards','a,n,ac,ax,be');
$x=(new WifiNetworkGroups($d))->inspect();
check(in_array('be',$x['technology']['supported'],true),'be support');
check($x['mlo']['state']==='not_reported','Wi-Fi 7 not MLO proof');
put($d,'Device.WiFi.X_TEST_MLO.Enable',true,true);
$x=(new WifiNetworkGroups($d))->inspect();
check($x['mlo']['candidate_count']===1,'MLO parameter identified');
check($x['mlo']['can_manage']===false,'MLO not writable until mapped');
check(WifiNetworkGroups::standards('Wi-Fi 7')===[],'marketing name rejected');
check(WifiNetworkGroups::standards('nonsense')===[],'invalid tokens rejected');
check(WifiNetworkGroups::standards('802.11be')===['be'],'be parsed');
check(WifiNetworkGroups::standards('anac')===['a','n','ac'],'compact tokens');
check(WifiNetworkGroups::standards(null)===[],'missing standards');
$empty=(new WifiNetworkGroups([]))->inspect();
check($empty['technology']['supported']===[],'empty remains unknown');
check($empty['device']['model']===null,'model not guessed');
put($d,'Device.WiFi.Radio.3.OperatingFrequencyBand','6GHz');
$x=(new WifiNetworkGroups($d))->inspect();
check(in_array('6',$x['bands_reported'],true),'6 GHz displayed as band');
$legacy=[];
put($legacy,'InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.Standard','bgn');
put($legacy,'InternetGatewayDevice.LANDevice.1.WLANConfiguration.2.X_HW_FrequencyBand','5.8GHz');
put($legacy,'InternetGatewayDevice.LANDevice.1.X_FH_SmartConnect.Enable',false,true);
$x=(new WifiNetworkGroups($legacy))->inspect();
check(in_array('n',$x['technology']['configured'],true),'legacy standard');
check($x['bands_reported']===['5'],'5.8 normalized only as band');
check($x['unified']['state']==='mapping_required','legacy disabled candidate not treated as available management');
put($legacy,'InternetGatewayDevice.LANDevice.1.X_FH_SmartConnect.Key','SENSITIVE',true);
$x=(new WifiNetworkGroups($legacy))->inspect();
check(!str_contains(json_encode($x),'SENSITIVE'),'arbitrary candidate value removed');
$deep=[];$path='Device.'.implode('.',array_fill(0,35,'Child'));put($deep,$path,'UNREAD');
check((new WifiNetworkGroups($deep))->inspect()['incomplete']===true,'depth limit marked incomplete');
$api=file_get_contents(__DIR__.'/../api/wifi-network-groups.php');
check(!str_contains($api,'setParameterValues'),'endpoint cannot submit writes');
check(!str_contains($api,'refreshObject'),'no task on GET');
check(str_contains($api,"header('Allow: GET')"),'non GET rejected');
check(str_contains($api,'SELECT role, active FROM users WHERE id = ?'),'db role check');
check(str_contains($api,'CURLOPT_FOLLOWLOCATION=>false'),'no redirect for credentials');
echo "PASS: $n checks\n";
file_put_contents(__DIR__.'/groups-fixture.json',json_encode(['success'=>true,'observed_at'=>'2026-09-20T12:00:00Z','data'=>(new WifiNetworkGroups($d))->inspect()],JSON_PRETTY_PRINT));
